### ISSUE TITLE
Libraries cannot be imported after installing with pip

### ISSUE THREAD

**Issue by biglemon29** [sparkfun/Qwiic_Ublox_Gps_Py#1]
After installing the qwiic_ublox_gps library via pip and trying to run the example code I get the error

`ModuleNotFoundError: No module named 'qwiic_gps_ublox`

I have also made sure to install the qwiic library and edit the boot config for clock stretching

**Comment by edspark** [comment]
Hello @biglemon29 . I'm currently rewriting this library so some modules might not be where they should be.  As it stands the library does not work because clock stretching for the I2C bus on the raspberry pi is not robust enough to handle the ublox modules. The ublox modules use clock stretching to its' limit due to the slow response time of receiving information from satellites. As a result the  library will be built around the serial and SPI data buses.

**Comment by biglemon29** [comment]
Great glad to hear! Any timeline of when it will be released?
