### ISSUE TITLE
Undisclosed Source and Wrong Licence

### ISSUE THREAD

**Issue by dalymople** [sparkfun/Qwiic_Ublox_Gps_Py#11]
This package appears to be heavily based on my package [dalymople/ubxtranslator](https://github.com/dalymople/ubxtranslator) but you have not provided attribution and have changed the licence type from GPL-3.0 License to MIT.

Can you please correct this.

**Comment by edspark** [comment]
Hello @dalymople,

I sincerely apologize for this oversight. In my rush to get this library functional due in large part because of your source code, I had forgotten to update license and attribution. Frankly I'm a bit embarrassed and will make sure to update this repository first thing this morning. Please understand that it was not my intention to let this go as long as it did without proper attribution, but I will make sure that it is stated in every place that it should be. I'll come back to close this issue when it's done.

**Comment by edspark** [comment]
Any place that the MIT license was mentioned has been replaced with the GNU GPL 3.0 license. I've also made sure to mention where relevant, how the code is dependent on the parsing capabilities of your source code. Again, thank you for allowing others to use your code (especially us). Please reopen and let me know if there's anything I've missed.

**Comment by dalymople** [comment]
No worries, thank you for fixing.
